### PR TITLE
Add Rider Home Screen Component

### LINKED ISSUE #3: (feat) Create the Rider Home Component
**Description**
Create the rider home page as designed in the mock-up, including setting up react navigation to allow for page navigation.

**Reason**
This should serve as a good jumping off and reference point for the creation of other page components as the style will be there, and the early implementation of React Navigation will make future development go smoother.

### PR DESCRIPTION
**Pull request by jaxcksn**
# Add Rider Home Screen Component
## Fixes
Fixes #3  by @jaxcksn 

## Description
Added the home screen component, React Navigation, several smaller components, Google Maps functionality, .env capabilities, and documentation.

## Checklist
 
- [X] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [X] My pull request targets the *default* branch of the repository (`main` or `master`).
- [X] My commit messages follow best practices.
- [X] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [X] I added or updated documentation (if applicable).
- [X] I tried running the project locally and verified that there are no
  visible errors.

## Developer Certificate of Origin

For the purposes of this DCO, "license" is equivalent to "license or public domain dedication," and "open source license" is equivalent to "open content license or public domain dedication."
<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by Guysnacho** [comment]
Hey Jackson, really good work but there's a slight problem. Its more about approachability than functionality. You build like a seasoned developer, from comments and annotations to folder naming and organization.

The problem is only maybe 2~3 people out of the entire team will end up participating because they'll get stuck trying to make custom components with consistent styling from scratch or trying to understand how you're passing props between components or the million other things that you're used to but they may not be. Lemme be clear, **_I'm they too_** 😂

All that to say, would you be willing to work with me to migrate to an already documented ui component library? We can configure a theme so styling is consistent. Using something like [UI Kitten](https://akveo.github.io/react-native-ui-kitten/docs/getting-started/what-is-ui-kitten#what-is-ui-kitten) or [React Native UI](https://github.com/wix/react-native-ui-lib) lowers the barrier of entry low enough that everyone can learn.

**Comment by jaxcksn** [comment]
Yeah of course, I converted this PR to a draft to see if I could implement an open source mapping SDK (to lower the barrier to entry) but if you want I can go ahead and replace some of the components made with UI Kitten. Let me see if UI Kitten has a figma library for me to update the mockups with too. 

I think the map functionality is still going to have a fair bit of complexity no matter what unfortunately.

**Comment by Guysnacho** [comment]
Oh you don't need to worry about major features like the map being complex. But thank you on understanding on the ui components, again if you want help or a peer programmer definitely lemme know.

**Comment by jaxcksn** [comment]
Ok @Guysnacho I figured we can put the UI library implementation into a separate issue / pull request. (There's been a lot of commits in this branch already).

**Pull request merged**
